# Generated by Django 4.2.9 on 2026-09-23 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseDrugReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=150)),
                ('reaction', models.TextField()),
                ('severity', models.CharField(default='Moderate', max_length=20)),
                ('reported_date', models.DateField(default=django.utils.timezone.now)),
                ('action_taken', models.CharField(blank=True, default='Discontinued medication', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=100)),
                ('reaction', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical / Anaphylactic')], default='HIGH', max_length=20)),
                ('diagnosed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('appointment_type', models.CharField(default='Follow-up Consultation', max_length=100)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No-show', 'No-show')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=150)),
                ('access_type', models.CharField(choices=[('ALL', 'Complete Medical & Prescription Records'), ('LAB_ONLY', 'Laboratory Results & Diagnostics Only'), ('PHARMACY_ONLY', 'Prescription & Dispensing Verification Only')], default='ALL', max_length=30)),
                ('status', models.CharField(choices=[('GRANTED', 'Granted'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='GRANTED', max_length=20)),
                ('granted_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-granted_date'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory_name', models.CharField(default='Apex Clinical Diagnostics', max_length=150)),
                ('report_title', models.CharField(max_length=150)),
                ('specimen_type', models.CharField(default='Blood (Serum)', max_length=50)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('ABNORMAL', 'Abnormal / Elevated'), ('CRITICAL', 'Critical Alert'), ('PENDING', 'Pending Review')], default='NORMAL', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
                ('reference_range', models.CharField(default='', max_length=50)),
                ('flag', models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Low', 'Low'), ('Critical', 'Critical')], default='Normal', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=150)),
                ('icd10_code', models.CharField(blank=True, default='', max_length=20)),
                ('diagnosed_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CHRONIC', 'Chronic'), ('RESOLVED', 'Resolved'), ('IN_REMISSION', 'In Remission')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DIAGNOSIS', 'Clinical Diagnosis'), ('HOSPITAL_VISIT', 'Hospitalization / Inpatient'), ('SURGERY', 'Surgical Procedure'), ('OUTPATIENT', 'Outpatient Visit'), ('IMPORTANT_EVENT', 'Critical Clinical Event')], default='DIAGNOSIS', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('facility_name', models.CharField(blank=True, default='RxCare Medical Center', max_length=150)),
                ('treating_physician', models.CharField(blank=True, default='Dr. Rahul Mehta', max_length=100)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blood_pressure_sys', models.PositiveIntegerField(default=120, help_text='mmHg (Systolic)')),
                ('blood_pressure_dia', models.PositiveIntegerField(default=80, help_text='mmHg (Diastolic)')),
                ('heart_rate', models.PositiveIntegerField(default=72, help_text='bpm')),
                ('blood_glucose', models.FloatField(default=110.0, help_text='mg/dL fasting/random')),
                ('bmi', models.FloatField(default=24.5, help_text='kg/m2')),
                ('temperature_f', models.FloatField(default=98.6)),
                ('spo2', models.PositiveIntegerField(default=98)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
