# Generated by Django 5.2.17 on 2026-09-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
