# Generated by Django 4.2.9 on 2026-09-23 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=150)),
                ('brand_name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=50)),
                ('dosage_form', models.CharField(default='Tablet', max_length=50)),
                ('route', models.CharField(default='Oral', max_length=50)),
                ('contraindications', models.TextField(blank=True, default='')),
                ('allergy_class', models.CharField(blank=True, default='', max_length=100)),
                ('renal_consideration', models.BooleanField(default=False)),
                ('hepatic_consideration', models.BooleanField(default=False)),
                ('typical_dose', models.CharField(blank=True, default='', max_length=150)),
                ('max_daily_dose', models.CharField(blank=True, default='', max_length=100)),
                ('lab_considerations', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['generic_name'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('distance_km', models.FloatField(default=0.8)),
                ('rating', models.FloatField(default=4.7)),
            ],
            options={
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['distance_km'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(max_length=40, unique=True)),
                ('doctor_name', models.CharField(default='Dr. Rahul Mehta', max_length=120)),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('general_instructions', models.TextField(blank=True, default='')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Finalized', 'Finalized'), ('Verified', 'Verified'), ('Partially Dispensed', 'Partially Dispensed'), ('Dispensed', 'Dispensed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=30)),
                ('qr_code_data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=150)),
                ('brand_name', models.CharField(blank=True, default='', max_length=150)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=80)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('route', models.CharField(default='Oral', max_length=50)),
                ('instructions', models.CharField(blank=True, default='', max_length=255)),
                ('is_dispensed', models.BooleanField(default=False)),
                ('dispensed_quantity', models.PositiveIntegerField(default=0)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_in', to='pharmacy.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.prescription')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicineInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('Low', 'Low Risk'), ('Moderate', 'Moderate Warning'), ('High', 'High Severity'), ('Critical', 'Critical / Contraindicated')], default='Moderate', max_length=20)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('medicine_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='pharmacy.medicine')),
                ('medicine_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='pharmacy.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='DispensingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(default='Apollo Care Pharmacy', max_length=150)),
                ('dispensed_items_summary', models.TextField(default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_events', to='pharmacy.prescription')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('IN_STOCK', 'In Stock'), ('LIMITED_STOCK', 'Limited Stock'), ('OUT_OF_STOCK', 'Out of Stock')], default='IN_STOCK', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_inventories', to='pharmacy.medicine')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='pharmacy.pharmacy')),
            ],
            options={
                'unique_together': {('pharmacy', 'medicine')},
            },
        ),
    ]
