# Generated by Django 5.2.17 on 2026-09-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='latitude',
            field=models.FloatField(default=12.9716),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='longitude',
            field=models.FloatField(default=77.5946),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='opening_hours',
            field=models.CharField(default='8:00 AM - 10:00 PM', max_length=50),
        ),
    ]
